# LiteLLM configuration for GitHub Copilot models
# Use "github_copilot/gpt-4o" for GitHub Copilot models
use_litellm: true  # Set to true to use LiteLLM instead of OpenAI client
model: "github_copilot/gpt-4o"
toc_check_page_num: 20
max_page_num_each_node: 10
max_token_num_each_node: 20000
if_add_node_id: "yes"
if_add_node_summary: "yes"
if_add_doc_description: "no"
if_add_node_text: "no"